# backend_greeniHouse/mosquitto/config/mosquitto.conf
listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all

# WebSocket listener
# listener 9001
# protocol websockets

listener 9001 0.0.0.0
protocol websockets
